app:   
    name: "lm-addresslookup-sapi"
    
https:
  host: "0.0.0.0"
  port: "8082"
  timeout: "30000"
  path: "/api/*"

keystore:
  path: "key_store.jks"
  alias: "mule-server"

limit:
  limit: "200"
  
db:
  host: "database-1.cpo3aaq626o7.eu-north-1.rds.amazonaws.com"
  port: "3306"
  username: "admin"
  database: "product"