{
  "headers": {
    "host": "localhost:8082",
    "connection": "keep-alive",
    "content-length": "658",
    "sec-ch-ua": "\"Not A(Brand\";v=\"99\", \"Microsoft Edge\";v=\"121\", \"Chromium\";v=\"121\"",
    "sec-ch-ua-platform": "\"Windows\"",
    "client_id": "7a92a323762e4b1884bac9561a490e73",
    "sec-ch-ua-mobile": "?0",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0",
    "client_secret": "764837F1BB9F45cDa9F10e9477B09FA7",
    "content-type": "application/json",
    "accept": "*/*",
    "origin": "https://localhost:8082",
    "sec-fetch-site": "same-origin",
    "sec-fetch-mode": "cors",
    "sec-fetch-dest": "empty",
    "referer": "https://localhost:8082/console/",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-US,en;q=0.9"
  },
  "clientCertificate": null,
  "method": "PATCH",
  "scheme": "https",
  "queryParams": {},
  "requestUri": "/api/products/0",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/products/0",
  "listenerPath": "/api/*",
  "relativePath": "/api/products/0",
  "localAddress": "/127.0.0.1:8082",
  "uriParams": {
    "id": "0"
  },
  "rawRequestUri": "/api/products/0",
  "rawRequestPath": "/api/products/0",
  "remoteAddress": "/127.0.0.1:65356",
  "requestPath": "/api/products/0"
}